influxdb_data:
    image: daocloud.io/koolay/influxdb:latest
    command: echo hello
    volumes:
     - /data


influxdb:
    image: daocloud.io/koolay/influxdb:latest
    expose:
     - "4444"
    ports:
    - "8083:8083"
    - "8086:8086"
    volumes_from:
     - influxdb_data

telegraf:
    image: daocloud.io/koolay/telegraf:latest
    volumes:
     - ./telegraf.toml:/config/telegraf.toml
    links:
     - influxdb
